# Generated by Django 5.0.2 on 2024-02-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_membership_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
