# Generated by Django 5.0.2 on 2024-02-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_membership_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='gadgets',
            field=models.ManyToManyField(related_name='gadgets', to='person.person'),
        ),
    ]
