# Generated by Django 5.0.2 on 2024-02-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_group_gadgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='gadgets',
            field=models.ManyToManyField(related_name='groups_gadgets', to='person.person'),
        ),
    ]
