# Generated by Django 5.0.2 on 2024-02-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_dream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='dreams',
            field=models.ManyToManyField(to='person.person'),
        ),
    ]
